export const ERROR_CODES = {
  // 🔐 Auth
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  SESSION_REVOKED: "SESSION_REVOKED",
  REFRESH_INVALID: "REFRESH_INVALID",
  UNAUTHORIZED: "UNAUTHORIZED",

  // 👤 User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_REVOKED: "USER_REVOKED",

  // 🔑 Permission
  FORBIDDEN: "FORBIDDEN",
  PERMISSION_DENIED: "PERMISSION_DENIED",

  // 📦 Generic
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
